---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springingboot
  labels:
    app: springingboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springingboot
  template:
    metadata:
      labels:
        app: springingboot
    spec:
      containers:
        - name: springingboot
          image: docker.io/phengbunath/springingboot:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
